package ${basePackage}.controller;

import ${basePackage}.dto.${dtoClass};
import ${collaboratorImport};
import jakarta.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST controller for ${entityName}.
 * Generated by REST API Generator.
 */
@RestController
@RequestMapping("${resourcePath}")
public class ${className} {

    private final ${collaboratorClass} collaborator;

    public ${className}(${collaboratorClass} collaborator) {
        this.collaborator = collaborator;
    }

    @GetMapping
    public Page<${dtoClass}> list(
            @RequestParam(defaultValue = "0")  int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(defaultValue = "id") String sortBy,
            @RequestParam(defaultValue = "asc") String sortDir,
            @RequestParam(required = false)    String filter
    ) {
        return collaborator.findAll(page, size, sortBy, sortDir, filter);
    }

    @GetMapping("/{id}")
    public ResponseEntity<${dtoClass}> findById(@PathVariable Long id) {
        return ResponseEntity.ok(${findByIdCall});
    }

    @GetMapping("/search")
    public Page<${dtoClass}> search(
            @RequestParam String filter,
            @RequestParam(defaultValue = "0")  int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(defaultValue = "id") String sortBy,
            @RequestParam(defaultValue = "asc") String sortDir
    ) {
        return collaborator.findAll(page, size, sortBy, sortDir, filter);
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public ${dtoClass} create(@Valid @RequestBody ${dtoClass} dto) {
        return ${createCall};
    }

    @PutMapping("/{id}")
    public ${dtoClass} update(@PathVariable Long id, @Valid @RequestBody ${dtoClass} dto) {
        return ${updateCall};
    }

    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void delete(@PathVariable Long id) {
        ${deleteCall}
    }
}
