package ${basePackage}.entity;

${imports}
/**
 * ${entityName} entity.
 * Generated by REST API Generator.
 */
${classAnnotations}@Entity
@Table(name = "${tableName}")
public class ${className} {

${idFieldBlock}${auditBlock}${fieldsBlock}${relationshipBlock}${noArgConstructorBlock}${constructorBlock}${gettersBlock}}
