package ${basePackage}.service;

import ${basePackage}.dto.${dtoClass};
import ${basePackage}.entity.${entityClass};
import ${basePackage}.error.ResourceNotFoundException;
import ${basePackage}.mapper.${mapperClass};
import ${basePackage}.repository.${repositoryClass};
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Service for ${entityName}.
 * Generated by REST API Generator.
 */
@Service
@Transactional(readOnly = true)
public class ${className} {

    private final ${repositoryClass} repository;
    private final ${mapperClass} mapper;

    public ${className}(${repositoryClass} repository, ${mapperClass} mapper) {
        this.repository = repository;
        this.mapper = mapper;
    }

    public Page<${dtoClass}> findAll(int page, int size, String sortBy, String sortDir, String filter) {
        Sort sort = "desc".equalsIgnoreCase(sortDir)
                ? Sort.by(sortBy).descending()
                : Sort.by(sortBy).ascending();
        Pageable pageable = PageRequest.of(Math.max(page, 0), Math.max(1, Math.min(size, 100)), sort);
        Specification<${entityClass}> spec = buildSpecification(filter);
        return repository.findAll(spec, pageable).map(mapper::toDto);
    }

    @Transactional
    public ${dtoClass} create(${dtoClass} dto) {
        ${entityClass} entity = mapper.toEntity(dto);
        return mapper.toDto(repository.save(entity));
    }

    public ${dtoClass} findById(Long id) {
        return repository.findById(id)
                .map(mapper::toDto)
                .orElseThrow(() -> new ResourceNotFoundException("${entityName}", "id", id));
    }

    @Transactional
    public ${dtoClass} update(Long id, ${dtoClass} dto) {
        ${entityClass} entity = repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("${entityName}", "id", id));
        mapper.updateEntityFromDto(dto, entity);
        return mapper.toDto(repository.save(entity));
    }

    @Transactional
    public void delete(Long id) {
        ${entityClass} entity = repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("${entityName}", "id", id));
        repository.delete(entity);
    }

    private Specification<${entityClass}> buildSpecification(String filter) {
        if (filter == null || filter.isBlank()) {
            return Specification.where(null);
        }
        String likePattern = "%" + filter.toLowerCase() + "%";
        return (root, query, cb) -> cb.or(
            ${filterPredicates}
        );
    }
}
